# generated by datamodel-codegen:
#   filename:  openapi.yaml
#
# DO NOT EDIT — regenerate with: make generate

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any, Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, Field, RootModel


class BackendType(StrEnum):
    vanilla_k8s = 'vanilla_k8s'
    openshell = 'openshell'


class CapabilitiesResponse(BaseModel):
    api_version: Annotated[str | None, Field(title='Api Version')] = 'v1'
    workloads: Annotated[list[str] | None, Field(title='Workloads')] = None
    result_events: Annotated[bool | None, Field(title='Result Events')] = True


class ClusterBindingRead(BaseModel):
    client_id: Annotated[str, Field(title='Client Id')]
    source_integration_id: Annotated[UUID, Field(title='Source Integration Id')]
    desired_revision: Annotated[int, Field(title='Desired Revision')]
    observed_revision: Annotated[int, Field(title='Observed Revision')]
    cluster_id: Annotated[UUID | None, Field(title='Cluster Id')]
    status: Annotated[str, Field(title='Status')]
    status_message: Annotated[str | None, Field(title='Status Message')]
    enabled: Annotated[bool, Field(title='Enabled')]
    updated_at: Annotated[AwareDatetime, Field(title='Updated At')]


class CaCertificate(RootModel[str]):
    root: Annotated[str, Field(max_length=65536, title='Ca Certificate')]


class ClusterBindingUpsert(BaseModel):
    revision: Annotated[int, Field(ge=1, title='Revision')]
    name: Annotated[str, Field(max_length=255, min_length=1, title='Name')]
    endpoint: Annotated[str, Field(max_length=2048, min_length=1, title='Endpoint')]
    namespace: Annotated[
        str,
        Field(
            max_length=63,
            min_length=1,
            pattern='^[a-z0-9]([-a-z0-9]*[a-z0-9])?$',
            title='Namespace',
        ),
    ]
    credential: Annotated[str | None, Field(title='Credential')] = ''
    ca_certificate: Annotated[CaCertificate | None, Field(title='Ca Certificate')] = None
    insecure_skip_tls_verify: Annotated[bool | None, Field(title='Insecure Skip Tls Verify')] = False
    project_ids: Annotated[list[UUID] | None, Field(title='Project Ids')] = None
    labels: Annotated[dict[str, str] | None, Field(title='Labels')] = None
    enabled: Annotated[bool | None, Field(title='Enabled')] = True


class KubernetesPlacement(BaseModel):
    type: Annotated[Literal['kubernetes'], Field(title='Type')] = 'kubernetes'
    namespace: Annotated[
        str,
        Field(
            description='Kubernetes namespace reserved for execution workloads',
            max_length=63,
            min_length=1,
            pattern='^[a-z0-9]([-a-z0-9]*[a-z0-9])?$',
            title='Namespace',
        ),
    ]
    node_selectors: Annotated[list[str] | None, Field(title='Node Selectors')] = None
    tolerations: Annotated[list[str] | None, Field(title='Tolerations')] = None


class RHELPlacement(BaseModel):
    type: Annotated[Literal['rhel'], Field(title='Type')] = 'rhel'


class TargetStatus(StrEnum):
    registering = 'registering'
    validating = 'validating'
    bootstrapping = 'bootstrapping'
    active = 'active'
    degraded = 'degraded'
    draining = 'draining'
    failed = 'failed'


class ValidationError(BaseModel):
    loc: Annotated[list[str | int], Field(title='Location')]
    msg: Annotated[str, Field(title='Message')]
    type: Annotated[str, Field(title='Error Type')]
    input: Annotated[Any | None, Field(title='Input')] = None
    ctx: Annotated[dict[str, Any] | None, Field(title='Context')] = None


class WorkItemCancelRequest(BaseModel):
    work_correlation_id: Annotated[UUID, Field(title='Work Correlation Id')]


class WorkItemStatus(StrEnum):
    pending = 'pending'
    claimed = 'claimed'
    dispatched = 'dispatched'
    cancel_requested = 'cancel_requested'
    reconciliation_required = 'reconciliation_required'
    completed = 'completed'
    failed = 'failed'
    cancelled = 'cancelled'


class WorkItemSubmit(BaseModel):
    request_id: Annotated[str, Field(max_length=200, min_length=1, title='Request Id')]
    work_correlation_id: Annotated[UUID, Field(title='Work Correlation Id')]
    workload_type: Annotated[Literal['script'], Field(title='Workload Type')] = 'script'
    payload: Annotated[dict[str, Any], Field(title='Payload')]


class ExecutionTargetRead(BaseModel):
    id: Annotated[UUID, Field(title='Id')]
    cluster_id: Annotated[UUID, Field(title='Cluster Id')]
    name: Annotated[str, Field(title='Name')]
    backend_type: BackendType
    endpoint: Annotated[str, Field(title='Endpoint')]
    placement: Annotated[
        KubernetesPlacement | RHELPlacement,
        Field(discriminator='type', title='Placement'),
    ]
    status: TargetStatus
    enabled: Annotated[bool, Field(title='Enabled')]
    is_default: Annotated[bool, Field(title='Is Default')]
    status_message: Annotated[str | None, Field(title='Status Message')]
    labels: Annotated[dict[str, str], Field(title='Labels')]
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    last_ran_at: Annotated[AwareDatetime | None, Field(title='Last Ran At')]


class HTTPValidationError(BaseModel):
    detail: Annotated[list[ValidationError] | None, Field(title='Detail')] = None


class WorkItemRead(BaseModel):
    id: Annotated[UUID, Field(title='Id')]
    project_id: Annotated[UUID, Field(title='Project Id')]
    request_id: Annotated[str, Field(title='Request Id')]
    work_correlation_id: Annotated[UUID, Field(title='Work Correlation Id')]
    status: WorkItemStatus
    result: Annotated[dict[str, Any] | None, Field(title='Result')]
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    claimed_at: Annotated[AwareDatetime | None, Field(title='Claimed At')]
    completed_at: Annotated[AwareDatetime | None, Field(title='Completed At')]
    resource_cleanup_status: Annotated[str, Field(title='Resource Cleanup Status')]
    resource_cleanup_error: Annotated[str | None, Field(title='Resource Cleanup Error')]
    completion_event_id: Annotated[UUID | None, Field(title='Completion Event Id')] = None
    state_revision: Annotated[int | None, Field(title='State Revision')] = None
